### ISSUE TITLE
to-do-list

### ISSUE THREAD

**Issue by mametur** [mametur/chat-forum-Mysql#3]
1. Node.js
- [x] Create a new project
- [x] sign-in & sign up 
- [x] serch users 
- [x] edit & delete 
- [x] Leave comment
2. UI
- [x] show sign-up message nicely
- [x] overflow user comments
- [x] use enter button to sign-up of sign-in
- [x] Toggle button for Log-out and day&night mode 
- [x]  display edit and delete button nicely
- [x]  show last comment when enter it
